on:
  pull_request:
    branches:
    - main
jobs:
  login:
    name: azure login
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.1.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # ClientId of the Azure Service principal created.
        # client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # TenantId of the Azure Service principal created.
        # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # Azure subscriptionId
        # subscription-id: # optional
        # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
        # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
        # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
        # auth-type: SERVICE_PRINCIPAL

    - name: Get credentials
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: 
          az keyvault certificate download --file "certificate.pem" --vault-name "COPSeattleKV" --name CRMCert
